#!bin/bash
#catFunction
MaximusSteal () {
	chance=$((1 + RANDOM % 20))
	if [ chance <= 3 ]; then
		(( birdCount = $birdCount - 1 ))
	fi
}

OfferToCat9 () {
	if [ birdCount > 1 }; then
		read -p "Would you like to share one bird with Cat 9? (y/n)" local answer
		case "$answer" in
			y|Y)
				echo "You decided to shared one bird with Cat 9. Maybe one day they'll thank you"
				(( birdCount = $birdCount - 1 ))
				echo
			;;
			n|N)
				echo "You decided to ignore the hunger Cat 9. Who knows what will come of this."
				echo
			;;
		esac
	fi
}

huntingHelp () {
	if (dayStart); then
		read -p "Would you like to ask for help from one of the other cats? (y/n)" local answer
		case "$answer" in
			y|Y)
				read -p "Which cat would you like to ask for help? (1-9)" local catNumber
				case "$catNumber" in
					1)
						echo "So you want "my" help, waste of space. Fine I will tell you how many birds there are but you must give me my fair share."
						local birdsNeeded
						echo "There are $nestCount birds today."
						(( birdsNeeded = $nestCount % 3 ))
						echo "You owe me $birdsNeeded birds or else..."
					;;
					2)
						echo "Sergent 10, I'm expcecting some big things out of you, so don't disapoint me you filthy maggot."
						
					;;
					3)
						echo "I will help you but first I have several condidtions that you must meet."
						local task
						#Insert three or so different "tests" that have to be performed
						#Each task will increase a counter 
						if [ task == 3 ]; then
							echo "Fine you pass. There is a bird $locateBird 
					;;
					4)
						
					;;
					5)
						
					;;
					6)
						
					;;
					7)
						
					;;
					8)
						
					;;
					9)
						
					;;
			;;
			n|N)
				echo "You decided not to get help today."
				echo
			;;
		esac
	fi
}
